### ISSUE TITLE
Doesn't let you log in.

### ISSUE THREAD

**Issue by shinrq** [Browncha023/EndInternetCensorship#18]
My friends and I have been using this website and loving it, the only thing is that when we try to use the proxy it doesn't let you log into anything. This renders it practically useless to us as you can't use it for anything like Netflix. Was wondering if this was a problem for us specifically or on your end.

**Comment by Browncha023** [comment]
So, this is a little complicated. I can't control what sites have login support as I'm not a proxy developer. I'm using the latest version of womginx (found [here](https://github.com/binary-person/womginx)). Login is still supported for some sites like discord, but otherwise you can open an issue there to see if they will update the proxy to support it (They likely won't). I'm sorry for the inconvenience.

**Comment by shinrq** [comment]
Ok thank you. Yeah, for most sites it just sends you back to the login screen. I will open an issue there and see if I can get it resolved, but thank you none the less. Love this project.
